services:
  trino-coordinator:
    image: trinodb/trino:latest
    container_name: trino-coordinator
    ports:
      - "8080:8080"
    volumes:
      - ./trino/coordinator-config:/etc/trino
    networks:
      - trino-network

  trino-worker-1:
    image: trinodb/trino:latest
    container_name: trino-worker-1
    volumes:
      - ./trino/worker-config:/etc/trino
      - ./trino/coordinator-config/catalog:/etc/trino/catalog
    depends_on:
      - trino-coordinator
    environment:
      - NODE_ID=worker-1
    networks:
      - trino-network

  trino-worker-2:
    image: trinodb/trino:latest
    container_name: trino-worker-2
    volumes:
      - ./trino/worker-config:/etc/trino
      - ./trino/coordinator-config/catalog:/etc/trino/catalog
    depends_on:
      - trino-coordinator
    environment:
      - NODE_ID=worker-2
    networks:
      - trino-network

  trino-worker-3:
    image: trinodb/trino:latest
    container_name: trino-worker-3
    volumes:
      - ./trino/worker-config:/etc/trino
      - ./trino/coordinator-config/catalog:/etc/trino/catalog
    depends_on:
      - trino-coordinator
    environment:
      - NODE_ID=worker-3
    networks:
      - trino-network

networks:
  trino-network:
    name: trino-network
    driver: bridge
